export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_EVENT = 'FETCH_EVENT';
export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const DELETE_BY_DATE_CREATORID = 'DELETE_BY_DATE_CREATORID';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_BY_SEARCH = 'FETCH_USERS_BY_SEARCH';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_CONVERSATIONS = 'FETCH_CONVERSATIONS';
export const FETCH_CONVERSATION = 'FETCH_CONVERSATION';
export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';

//projects
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

//tasks
export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASK = 'FETCH_TASK';
export const CREATE_TASK = 'CREATE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
